services:
  - type: web
    name: cccd-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host=0.0.0.0 --port=10101"
    envVars:
      - key: PORT
        value: 10101
